services:
  openniimstudio:
    image: forgejo.syncedmedia.be/matieke/openniimstudio:0.3.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openniimstudio
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - openniimstudio_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  openniimstudio_data:
    name: catlabel_data
